apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: taskflow-dev

resources:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: dev

patches:
  - target:
      kind: Deployment
      name: taskflow-api
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: APP_ENV
            value: dev
          - name: LOG_LEVEL
            value: debug