apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: taskflow-backend
  title: TaskFlow API
  description: FastAPI backend exposing /health and /api/tasks endpoints.
  annotations:
    github.com/project-slug: sudipto2104/platform-engineering-portfolio
    backstage.io/source-location: url:https://github.com/sudipto2104/platform-engineering-portfolio/tree/main/07-introduction-containers-docker/taskflow-stack/backend
    backstage.io/kubernetes-id: taskflow-backend
    backstage.io/kubernetes-namespace: taskflow
  tags:
    - python
    - fastapi
    - rest
  links:
    - url: http://localhost:8080/health
      title: Health Check
      icon: docs
    - url: http://localhost:8080/docs
      title: OpenAPI Docs
      icon: docs
spec:
  type: service
  lifecycle: production
  owner: group:platform-team
  system: taskflow
  providesApis:
    - taskflow-rest-api
  dependsOn:
    - resource:taskflow-postgres
    - resource:taskflow-redis