apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-api
  namespace: taskflow-lab2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskflow-api
  template:
    metadata:
      labels:
        app: taskflow-api
    spec:
      containers:
        - name: api
          image: taskflow-api:week7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: taskflow-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: taskflow-secrets
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: taskflow-secrets
                  key: REDIS_URL
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 5