apiVersion: v1
kind: Secret
metadata:
  name: taskflow-secrets
  namespace: taskflow-lab2
type: Opaque
stringData:
  POSTGRES_PASSWORD: taskflow_k8s_dev
  DATABASE_URL: postgresql://taskflow:taskflow_k8s_dev@postgres:5432/taskflow
  REDIS_URL: redis://redis:6379/0