upstream taskflow_api {
    server taskflow:8080;
}

server {
    listen 80;
    server_name taskflow.local;

    location /health {
        proxy_pass http://taskflow_api/health;
        proxy_set_header Host $host;
    }

    location /api/ {
        proxy_pass http://taskflow_api/api/;
        proxy_set_header Host $host;
    }

    location / {
        return 200 'TaskFlow Week 2 — nginx reverse proxy\n';
        add_header Content-Type text/plain;
    }
}