apiVersion: v1
kind: Secret
metadata:
  name: taskflow-secrets
  namespace: taskflow
type: Opaque
stringData:
  POSTGRES_PASSWORD: taskflow_prod_lab
  DATABASE_URL: postgresql://taskflow:taskflow_prod_lab@postgres:5432/taskflow
  REDIS_URL: redis://redis:6379/0