apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taskflow-ingress
  namespace: taskflow-prod
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/rate-limit: "100"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - app.taskflow.example.com
      secretName: taskflow-tls
  rules:
    - host: app.taskflow.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: taskflow-api
                port:
                  number: 8080
          - path: /health
            pathType: Exact
            backend:
              service:
                name: taskflow-api
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: taskflow-ui
                port:
                  number: 80