apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskflow-production
  namespace: argocd
spec:
  project: taskflow
  source:
    repoURL: https://github.com/sudipto2104/platform-engineering-portfolio
    targetRevision: main
    path: 16-gitops-argocd/lab-kustomize-argocd-multenv/solutions/kustomize/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: taskflow-production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  # Production: manual sync option for change control
  # syncPolicy: {}  # uncomment to require manual promotion