{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskflow.fullname" . }}-api
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "taskflow.api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: 8080
      targetPort: 8080
{{- end }}