apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "taskflow.fullname" . }}-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "taskflow.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.global.environment | quote }}
  LOG_LEVEL: {{ .Values.api.env.logLevel | quote }}
  POSTGRES_HOST: postgres
  REDIS_HOST: redis