{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskflow.fullname" . }}-ui
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "taskflow.ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type }}
  selector:
    app.kubernetes.io/component: ui
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: 80
{{- end }}