apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: taskflow-vault-secrets
  namespace: taskflow
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.vault.svc:8200"
    roleName: "taskflow-csi"
    objects: |
      - objectName: "database-config"
        secretPath: "secret/data/taskflow/app/database"
        secretKey: "username"
      - objectName: "database-password"
        secretPath: "secret/data/taskflow/app/database"
        secretKey: "password"
  secretObjects:
    - secretName: taskflow-vault-sync
      type: Opaque
      data:
        - objectName: database-config
          key: DB_USER
        - objectName: database-password
          key: DB_PASSWORD
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-api-csi
  namespace: taskflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskflow-api-csi
  template:
    metadata:
      labels:
        app: taskflow-api-csi
    spec:
      serviceAccountName: taskflow-api
      containers:
        - name: api
          image: taskflow-api:week7
          envFrom:
            - secretRef:
                name: taskflow-vault-sync
          volumeMounts:
            - name: vault-secrets
              mountPath: /mnt/secrets
              readOnly: true
      volumes:
        - name: vault-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: taskflow-vault-secrets