# TaskFlow application servers (Week 11 EC2 private app tier)
[taskflow_app]
app1 ansible_host=10.30.10.10 ansible_user=ec2-user
app2 ansible_host=10.30.10.11 ansible_user=ec2-user

[taskflow_app:vars]
ansible_python_interpreter=/usr/bin/python3
taskflow_version=week12-ansible