apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-api-dynamic
  namespace: taskflow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskflow-api-dynamic
  template:
    metadata:
      labels:
        app: taskflow-api-dynamic
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "taskflow-api"
        vault.hashicorp.com/agent-inject-secret-db-creds: "database/creds/taskflow-app"
        vault.hashicorp.com/agent-inject-template-db-creds: |
          {{- with secret "database/creds/taskflow-app" -}}
          export DATABASE_URL="postgresql://{{ .Data.username }}:{{ .Data.password }}@postgres.taskflow.svc:5432/taskflow"
          export DB_LEASE_ID="{{ .Env.RENEW_TOKEN }}"
          {{- end }}
        vault.hashicorp.com/agent-inject-token: "true"
    spec:
      serviceAccountName: taskflow-api
      containers:
        - name: api
          image: taskflow-api:week7
          command: ["/bin/sh", "-c"]
          args:
            - source /vault/secrets/db-creds && exec uvicorn main:app --host 0.0.0.0 --port 8080
          ports:
            - containerPort: 8080