apiVersion: v1
kind: ServiceAccount
metadata:
  name: taskflow-api
  namespace: taskflow
  labels:
    app.kubernetes.io/part-of: taskflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: taskflow-vault-auth
  namespace: taskflow
rules:
  - apiGroups: [""]
    resources: ["serviceaccounts/token"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: taskflow-vault-auth
  namespace: taskflow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: taskflow-vault-auth
subjects:
  - kind: ServiceAccount
    name: taskflow-api
    namespace: taskflow